/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package de.teelekom.coffeerating.graphics;

import javax.swing.JPanel;

/**
 *
 * @author deter
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form StartPage2
     */
    public LoginPanel lgnPanel;
    public  MainFrame mainFrame;
    
    public StartPage() {
        
        initComponents();
       lgnPanel = new LoginPanel();
        mainFrame = new MainFrame();
       

        add(lgnPanel, "Page1");
        add(mainFrame, "Page2"); 
        
        setTitle("CoffeeRating - Login");
	setDefaultCloseOperation(EXIT_ON_CLOSE);	
	setVisible(true);
	setResizable(false);
    }
    public JPanel getCardPanel() {
        return cardPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cardPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LoginPanel lgnPanel = new LoginPanel();
        MainFrame mainFrame = new MainFrame();

        cardPanel.add(lgnPanel, "Page1");
        cardPanel.add(mainFrame, "Page2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public LoginPanel getLgnPanel() {
        return lgnPanel;
    }

    public MainFrame getMainFrame() {
        return mainFrame;
    }
    
    
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    // End of variables declaration//GEN-END:variables
}
